[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php-fpm"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
